version: 2


jobs:
  ui:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.15.3-browsers

    steps:
      - checkout
      - run: yarn install --immutable --immutable-cache
      - run: yarn check:deps
      - run: yarn lint
      - run: yarn test
      - run: yarn lib
      - run: yarn dist
      - run: yarn pub


workflows:
  version: 2
  dev:
    jobs:
      - ui
